SCSI Dump Usability Enhancements & Cleanup
PiSCSI/piscsi pull request #1026
Opened 2022-12-08 16:50 UTC by akuker

- Fix for weird corner case - when executing the arm binary on an x86_64 host, PiSCSI will throw an exception while trying to initialize the GPIO bus. This isn't a valid use case, so just handling the exception and aborting execution. (TIL - Ubuntu 22 on x86_64 will still execute an ARM binary. It seems to spin up Qemu in the background to try to run the executable)
- Rename RasDump to ScsiDump
- Add total time and transfer rate to the output of scsidump
- Create a .properties file when backing up a drive. This can be used to more closely emulate the original drive.
- Added examples to man page + some cleanup/clarification

2022-12-08 19:13 UTC, uweseimet commented on cpp/test/test_shared.cpp
> -void CreateTempFileWithData(const string& filename, vector<uint8_t> &data)
I would appreciate if we were not reverting C++-style conventions for pointers and references back to C-style. We have C++ style almost everywhere now, and it's not just Bjarne Stroustrup who says:
```
A typical C programmer writes int *p; and explains it *p is what is the int emphasizing syntax, and may point to the C (and C++) declaration grammar to argue for the correctness of the style. Indeed, the * binds to the name p in the grammar.

A typical C++ programmer writes int* p; and explains it p is a pointer to an int emphasizing type. Indeed the type of p is int*. I clearly prefer that emphasis and see it as important for using the more advanced parts of C++ well.
```
but also IBM, cpppreference.com, ...

2022-12-08 19:16 UTC, uweseimet commented on cpp/scsidump/scsidump_core.h
> +    const string divider_str = "----------------------------------------";
Can this string be static?

2022-12-08 19:18 UTC, uweseimet commented on doc/scsidump.1
> +Run in restore mode. Defaults to download mode if not specified.
I don't think "download" is a good term. The common terms are dump/restore, just as the names of the respective UNIX commands. Downloading is quite specific for the file downloads in the internet.

2022-12-08 19:20 UTC, uweseimet commented on doc/scsidump_man_page.txt
> +       When operating in download mode, scsidump will copy all data from a remote SCSI drive to an image on the local filesystem. Additionally, it will generate a .properties file that can be used to
Is the creation of the .properties file mandatory? It should not be because not everybody (not just not me) would wants unexpected files to be created.

2022-12-08 19:21 UTC, uweseimet requested changes
Please see my comments.

2022-12-08 19:38 UTC, akuker commented on cpp/scsidump/scsidump_core.h
> +    struct inquiry_info_struct {
Its used in the test procedure. Suggestions for a better way to make it accessible to the test procedure?

2022-12-08 19:42 UTC, akuker commented on cpp/test/test_shared.cpp
> -void CreateTempFileWithData(const string& filename, vector<uint8_t> &data)
Are you saying that you prefer this:
```
void CreateTempFileWithData(const string& filename, vector<uint8_t>& data)
```
over this?
```
void CreateTempFileWithData(const string &filename, vector<uint8_t> &data)
```

Currently, its the clang formatting configuration that is doing this, so I'll need to investigate. But, I wanted to double check I'm understanding the comment first.

2022-12-08 19:45 UTC, uweseimet commented on cpp/scsidump/scsidump_core.h
> +    struct inquiry_info_struct {
In this case (tests also using it) there might be no alternative. In general an implementation should not have weak points just because of unit tests. If datat structures are/should be private from the implementation perspective (like in this case) tests should be coded in a way that they do not need to access these private structures. This is best practices as far as I know, and it makes sense. Otherwise you end up with a lot of data being public just because of the tests, which is defeating the idea of encapsulation.

2022-12-08 19:49 UTC, uweseimet commented on cpp/test/test_shared.cpp
> -void CreateTempFileWithData(const string& filename, vector<uint8_t> &data)
Yes, that's what I (and others like Stroustrup) are saying for pointers (*) and references (&) in C++. (If you google for it you will find several hits.) When using "&" as address operator it's different, but for "&" denoting a reference it should directly follow the type.

2022-12-08 19:53 UTC, akuker commented on cpp/test/test_shared.cpp
> -void CreateTempFileWithData(const string& filename, vector<uint8_t> &data)
Sounds good. I'll work on updating that configuration.

2022-12-08 19:57 UTC, uweseimet commented on cpp/scsidump/scsidump_core.h
> +    struct inquiry_info_struct {
Just one anecdotal note on this, because I just remembered: In a job interview I had a long time ago how to deal with a similar issue was a subject. It was essentially a private constant string that was part of the implementation. The string content was also required in a unit test. The preferred solution was to have a copy of the string (duplication) in the test, so that the original string could stay private.
In this particular case using a copy has also another benefit: If you use the same public string for your test, if somebody changes the string declaration your code may be wrong, but the test still passes. You will miss the code modification. With a copy for the test it would have been revealed that something in the code was changed,.

2022-12-08 20:12 UTC, uweseimet commented
A general remark, not specific to this PR, but also concerning this PR: For functional extensions like in this case (property file) it might be good to have a ticket first because:

- Others (not only somebody involved in the review or not even a developer) can provide useful comments
- Changes to already implemented new code can be avoided, because the implementation goal can be adjusted before starting the implemention. This saves time because you do not implement something (at least not that often) that you later may have to change.
- Comments in tickets IMHO are more informal than in reviews, which makes it easier to talk about changes. Once you have a PR, as a reviewer I usually do not want to block something, and requesting changes is more unpleasant than in a ticket. (At least for me.)

Just my two cents.

2022-12-08 23:19 UTC, akuker commented on cpp/scsidump/scsidump_core.h
> +    struct inquiry_info_struct {
In this case its a struct, not data. Another solution would be to move it out of the class definition completely.

2022-12-08 23:28 UTC, akuker commented on cpp/test/test_shared.cpp
> -void CreateTempFileWithData(const string& filename, vector<uint8_t> &data)
Should now be updated.

2022-12-08 23:30 UTC, akuker commented on cpp/test/test_shared.cpp
> +    std::ifstream in_fs(temp_file);
Fixed.

2022-12-08 23:30 UTC, akuker commented on cpp/scsidump/scsidump_core.h
> +    const string divider_str = "----------------------------------------";
Fixed.

2022-12-08 23:30 UTC, akuker commented on doc/scsidump.1
> +Run in restore mode. Defaults to download mode if not specified.
Changed to dump

2022-12-08 23:31 UTC, akuker commented on doc/scsidump_man_page.txt
> +       When operating in download mode, scsidump will copy all data from a remote SCSI drive to an image on the local filesystem. Additionally, it will generate a .properties file that can be used to
Now requires '-p' argument in order to enable this feature.

2022-12-09 09:29 UTC, uweseimet commented on cpp/scsidump/scsidump_core.h
> +    struct inquiry_info_struct {
I don't object keeping the code as it is if there is no convenient alternative.

2022-12-09 09:30 UTC, uweseimet commented
@akuker Thank you four addressing my comments.

2022-12-09 09:31 UTC, uweseimet approved these changes

2022-12-09 15:50 UTC, akuker commented
@uweseimet - Thank you for reviewing!! I'll try to do a better job of writing up issues before implementing things

2022-12-09 15:50 UTC, merged