Spanish translation
PiSCSI/piscsi pull request #1181
Opened 2023-07-03 12:35 UTC by n4al

2023-07-03 19:03 UTC, rdmark commented on python/web/src/translations/es/LC_MESSAGES/messages.po
> +"Consulte <a href=“%(url)s” target=“_blank”>Wiki</a> para obtener más "
It seems like typographic quotation marks made it into this string. This prevents this hyperlink from working. (I tested it.)

This is not a newly introduced issue with this changeset, of course, but I think it's a good idea to fix it now.

2023-07-03 19:03 UTC, rdmark commented on python/web/src/translations/es/LC_MESSAGES/messages.po
> +"href=“%(url)s”>GitHub</a>."
More typographic quotation marks!

2023-07-03 19:03 UTC, rdmark commented on python/web/src/translations/es/LC_MESSAGES/messages.po
> +"Consulte <a href=“%(url)s” target=“_blank”>documentación de la wiki</a> "
More typographic quotation marks. You may want to do a search&replace in the file.

2023-07-03 19:04 UTC, rdmark requested changes
Please replace the typographic quotation marks with standard quotation marks.

2023-07-05 01:04 UTC, rdmark commented on hw/README.md
> -https://github.com/PiSCSI/piscsi-hw
It seems like you mistakenly removed this README! Please revert this change.

2023-07-05 01:05 UTC, rdmark commented on python/web/src/translations/es/LC_MESSAGES/messages.po
> -"El Nombre del Sistema es el nombre de host “bonito” si está configurado, con un "
FWIW it's fine to use typographic quotation marks in this string since they're not part of html syntax. :)

2023-07-05 04:20 UTC, n4al commented on python/web/src/translations/es/LC_MESSAGES/messages.po
> -"El Nombre del Sistema es el nombre de host “bonito” si está configurado, con un "
To be completely honest, I have no clue how those quotation marks got in, in the first place, so I'd prefer just to get rid of them.

2023-07-05 04:21 UTC, n4al commented on hw/README.md
> -https://github.com/PiSCSI/piscsi-hw
I think I'll just get rid of this branch and do it from the beginning, correctly :)

2023-07-05 04:22 UTC, closed without merging