Multiple fixes for ModeSelect
PiSCSI/piscsi pull request #1405
Opened 2023-12-25 11:30 UTC by kkaempf

This PR covers multiple issues

- The DEC Alpha SRM console (aka BIOS) calls ModeSelect6 with no payload

- OpenVMS Alpha calls ModeSelect6 with a page code of 1

- ModeSelect had an off-by-one error in computing the length

2023-12-26 23:31 UTC, rdmark requested changes
The code changes look reasonable to me, given your reading of the SCSI spec.

Can you please update the unit tests to get them passing with this new interpretation of the expected behavior? Please let us know if you need help getting set up with googletest locally.

2023-12-27 20:30 UTC, kkaempf commented
@rdmark frankly, I'm at loss with fixing the tests :-( Is there any documentation ?

2023-12-28 07:45 UTC, rdmark commented
@kkaempf The closest we have to documentation is the issue ticket where the tests were initially introduced! https://github.com/PiSCSI/piscsi/issues/794

Running the tests should be as easy as installing the googletest libraries, and then running `make test`. You can also see the failing CI jobs here in this PR.

The actual test code should be fairly self-explanatory I think, but let me know if you need further pointers ;)

2024-01-04 15:38 UTC, kkaempf commented
The test output is quite unhelpful 😞 
```
[ RUN      ] ScsiCommandUtilTest.ModeSelect6
unknown file: Failure
C++ exception with description "std::exception" thrown in the test body.
[  FAILED  ] ScsiCommandUtilTest.ModeSelect6 (0 ms)

```

2024-01-04 15:57 UTC, kkaempf commented
Tests fixed (somewhat hackish imho)

2024-01-05 08:55 UTC, rdmark commented on cpp/test/scsi_command_util_test.cpp
> +	buf[13] = 10,
Should end with a semicolon, not a comma. :)

2024-01-05 08:56 UTC, rdmark commented
@kkaempf What makes you say the tests are hackish?

2024-01-05 10:24 UTC, kkaempf commented
> @kkaempf What makes you say the tests are hackish?

I can't say (yet ?) that I actually know what I'm doing there 🙈

2024-01-05 13:04 UTC, kkaempf commented
This should be complete now I believe.

2024-01-07 04:32 UTC, rdmark approved these changes
Thanks for your contribution!

2024-01-07 04:35 UTC, rdmark commented
Rebasing with the `develop` branch. This is where all new code goes. We then rebase with `main` after each stable release.

2024-01-07 06:06 UTC, merged